//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Process.TyGiaServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.TyGiaServiceRef.TyGiaRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Action ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ClientType ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.DonViSuDung CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Function FunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MngDeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Module ModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NgayLamViecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OprDeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestSecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.BusinessConstant.LoaiNguoiSuDung UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Action Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMAC {
            get {
                return this.ClientMACField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientMACField, value) != true)) {
                    this.ClientMACField = value;
                    this.RaisePropertyChanged("ClientMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.DonViSuDung Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((this.CompanyField.Equals(value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeField, value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Function Function {
            get {
                return this.FunctionField;
            }
            set {
                if ((this.FunctionField.Equals(value) != true)) {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MngDeptCode {
            get {
                return this.MngDeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MngDeptCodeField, value) != true)) {
                    this.MngDeptCodeField = value;
                    this.RaisePropertyChanged("MngDeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Module Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayLamViec {
            get {
                return this.NgayLamViecField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayLamViecField, value) != true)) {
                    this.NgayLamViecField = value;
                    this.RaisePropertyChanged("NgayLamViec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OprDeptCode {
            get {
                return this.OprDeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OprDeptCodeField, value) != true)) {
                    this.OprDeptCodeField = value;
                    this.RaisePropertyChanged("OprDeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestDateTime {
            get {
                return this.RequestDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDateTimeField, value) != true)) {
                    this.RequestDateTimeField = value;
                    this.RaisePropertyChanged("RequestDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestSecurityKey {
            get {
                return this.RequestSecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestSecurityKeyField, value) != true)) {
                    this.RequestSecurityKeyField = value;
                    this.RaisePropertyChanged("RequestSecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.BusinessConstant.LoaiNguoiSuDung UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TyGiaRequest", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.TyGia.Messages")]
    [System.SerializableAttribute()]
    public partial class TyGiaRequest : Presentation.Process.TyGiaServiceRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.DC_TY_GIA[] lstTyGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.DC_TY_GIA objTyGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.TY_GIA_CT objTyGiaCTField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.DC_TY_GIA[] lstTyGia {
            get {
                return this.lstTyGiaField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTyGiaField, value) != true)) {
                    this.lstTyGiaField = value;
                    this.RaisePropertyChanged("lstTyGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.DC_TY_GIA objTyGia {
            get {
                return this.objTyGiaField;
            }
            set {
                if ((object.ReferenceEquals(this.objTyGiaField, value) != true)) {
                    this.objTyGiaField = value;
                    this.RaisePropertyChanged("objTyGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.TY_GIA_CT objTyGiaCT {
            get {
                return this.objTyGiaCTField;
            }
            set {
                if ((object.ReferenceEquals(this.objTyGiaCTField, value) != true)) {
                    this.objTyGiaCTField = value;
                    this.RaisePropertyChanged("objTyGiaCT");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DC_TY_GIA", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class DC_TY_GIA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTHUC_NIEM_YETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOAI_TGIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_QLYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_TAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_LOAI_TIENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_TGIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_BGHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_NVUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_BANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TY_GIA_BQUANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TY_GIA_DGIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_MUAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTHUC_NIEM_YET {
            get {
                return this.HTHUC_NIEM_YETField;
            }
            set {
                if ((object.ReferenceEquals(this.HTHUC_NIEM_YETField, value) != true)) {
                    this.HTHUC_NIEM_YETField = value;
                    this.RaisePropertyChanged("HTHUC_NIEM_YET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOAI_TGIA {
            get {
                return this.LOAI_TGIAField;
            }
            set {
                if ((object.ReferenceEquals(this.LOAI_TGIAField, value) != true)) {
                    this.LOAI_TGIAField = value;
                    this.RaisePropertyChanged("LOAI_TGIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_QLY {
            get {
                return this.MA_DVI_QLYField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_QLYField, value) != true)) {
                    this.MA_DVI_QLYField = value;
                    this.RaisePropertyChanged("MA_DVI_QLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_TAO {
            get {
                return this.MA_DVI_TAOField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_TAOField, value) != true)) {
                    this.MA_DVI_TAOField = value;
                    this.RaisePropertyChanged("MA_DVI_TAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_LOAI_TIEN {
            get {
                return this.MA_LOAI_TIENField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_LOAI_TIENField, value) != true)) {
                    this.MA_LOAI_TIENField = value;
                    this.RaisePropertyChanged("MA_LOAI_TIEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_CNHAT {
            get {
                return this.NGAY_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_CNHATField, value) != true)) {
                    this.NGAY_CNHATField = value;
                    this.RaisePropertyChanged("NGAY_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_NHAP {
            get {
                return this.NGAY_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_NHAPField, value) != true)) {
                    this.NGAY_NHAPField = value;
                    this.RaisePropertyChanged("NGAY_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_TGIA {
            get {
                return this.NGAY_TGIAField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_TGIAField, value) != true)) {
                    this.NGAY_TGIAField = value;
                    this.RaisePropertyChanged("NGAY_TGIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_CNHAT {
            get {
                return this.NGUOI_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_CNHATField, value) != true)) {
                    this.NGUOI_CNHATField = value;
                    this.RaisePropertyChanged("NGUOI_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_NHAP {
            get {
                return this.NGUOI_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_NHAPField, value) != true)) {
                    this.NGUOI_NHAPField = value;
                    this.RaisePropertyChanged("NGUOI_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_BGHI {
            get {
                return this.TTHAI_BGHIField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_BGHIField, value) != true)) {
                    this.TTHAI_BGHIField = value;
                    this.RaisePropertyChanged("TTHAI_BGHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_NVU {
            get {
                return this.TTHAI_NVUField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_NVUField, value) != true)) {
                    this.TTHAI_NVUField = value;
                    this.RaisePropertyChanged("TTHAI_NVU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_BAN {
            get {
                return this.TY_GIA_BANField;
            }
            set {
                if ((this.TY_GIA_BANField.Equals(value) != true)) {
                    this.TY_GIA_BANField = value;
                    this.RaisePropertyChanged("TY_GIA_BAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TY_GIA_BQUAN {
            get {
                return this.TY_GIA_BQUANField;
            }
            set {
                if ((this.TY_GIA_BQUANField.Equals(value) != true)) {
                    this.TY_GIA_BQUANField = value;
                    this.RaisePropertyChanged("TY_GIA_BQUAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TY_GIA_DGIA {
            get {
                return this.TY_GIA_DGIAField;
            }
            set {
                if ((this.TY_GIA_DGIAField.Equals(value) != true)) {
                    this.TY_GIA_DGIAField = value;
                    this.RaisePropertyChanged("TY_GIA_DGIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_MUA {
            get {
                return this.TY_GIA_MUAField;
            }
            set {
                if ((this.TY_GIA_MUAField.Equals(value) != true)) {
                    this.TY_GIA_MUAField = value;
                    this.RaisePropertyChanged("TY_GIA_MUA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TY_GIA_CT", Namespace="http://schemas.datacontract.org/2004/07/BusinessServices.TyGia.DTO")]
    [System.SerializableAttribute()]
    public partial class TY_GIA_CT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.DANH_SACH_TY_GIA_CT[] DSACH_TY_GIA_CTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HINH_THUC_NIEM_YETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TY_GIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOAI_TY_GIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] LST_ID_XOAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LST_MA_THIENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_QLYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_TAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_LOAI_TIENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_AP_DUNGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRANG_THAI_BAN_GHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRANG_THAI_NGHIEP_VUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_BANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_BQUANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_DGIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_MUAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.DANH_SACH_TY_GIA_CT[] DSACH_TY_GIA_CT {
            get {
                return this.DSACH_TY_GIA_CTField;
            }
            set {
                if ((object.ReferenceEquals(this.DSACH_TY_GIA_CTField, value) != true)) {
                    this.DSACH_TY_GIA_CTField = value;
                    this.RaisePropertyChanged("DSACH_TY_GIA_CT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HINH_THUC_NIEM_YET {
            get {
                return this.HINH_THUC_NIEM_YETField;
            }
            set {
                if ((object.ReferenceEquals(this.HINH_THUC_NIEM_YETField, value) != true)) {
                    this.HINH_THUC_NIEM_YETField = value;
                    this.RaisePropertyChanged("HINH_THUC_NIEM_YET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TY_GIA {
            get {
                return this.ID_TY_GIAField;
            }
            set {
                if ((this.ID_TY_GIAField.Equals(value) != true)) {
                    this.ID_TY_GIAField = value;
                    this.RaisePropertyChanged("ID_TY_GIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOAI_TY_GIA {
            get {
                return this.LOAI_TY_GIAField;
            }
            set {
                if ((object.ReferenceEquals(this.LOAI_TY_GIAField, value) != true)) {
                    this.LOAI_TY_GIAField = value;
                    this.RaisePropertyChanged("LOAI_TY_GIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] LST_ID_XOA {
            get {
                return this.LST_ID_XOAField;
            }
            set {
                if ((object.ReferenceEquals(this.LST_ID_XOAField, value) != true)) {
                    this.LST_ID_XOAField = value;
                    this.RaisePropertyChanged("LST_ID_XOA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LST_MA_THIEN {
            get {
                return this.LST_MA_THIENField;
            }
            set {
                if ((object.ReferenceEquals(this.LST_MA_THIENField, value) != true)) {
                    this.LST_MA_THIENField = value;
                    this.RaisePropertyChanged("LST_MA_THIEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_QLY {
            get {
                return this.MA_DVI_QLYField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_QLYField, value) != true)) {
                    this.MA_DVI_QLYField = value;
                    this.RaisePropertyChanged("MA_DVI_QLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_TAO {
            get {
                return this.MA_DVI_TAOField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_TAOField, value) != true)) {
                    this.MA_DVI_TAOField = value;
                    this.RaisePropertyChanged("MA_DVI_TAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_LOAI_TIEN {
            get {
                return this.MA_LOAI_TIENField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_LOAI_TIENField, value) != true)) {
                    this.MA_LOAI_TIENField = value;
                    this.RaisePropertyChanged("MA_LOAI_TIEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_AP_DUNG {
            get {
                return this.NGAY_AP_DUNGField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_AP_DUNGField, value) != true)) {
                    this.NGAY_AP_DUNGField = value;
                    this.RaisePropertyChanged("NGAY_AP_DUNG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_CNHAT {
            get {
                return this.NGAY_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_CNHATField, value) != true)) {
                    this.NGAY_CNHATField = value;
                    this.RaisePropertyChanged("NGAY_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_NHAP {
            get {
                return this.NGAY_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_NHAPField, value) != true)) {
                    this.NGAY_NHAPField = value;
                    this.RaisePropertyChanged("NGAY_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_CNHAT {
            get {
                return this.NGUOI_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_CNHATField, value) != true)) {
                    this.NGUOI_CNHATField = value;
                    this.RaisePropertyChanged("NGUOI_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_NHAP {
            get {
                return this.NGUOI_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_NHAPField, value) != true)) {
                    this.NGUOI_NHAPField = value;
                    this.RaisePropertyChanged("NGUOI_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANG_THAI_BAN_GHI {
            get {
                return this.TRANG_THAI_BAN_GHIField;
            }
            set {
                if ((object.ReferenceEquals(this.TRANG_THAI_BAN_GHIField, value) != true)) {
                    this.TRANG_THAI_BAN_GHIField = value;
                    this.RaisePropertyChanged("TRANG_THAI_BAN_GHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANG_THAI_NGHIEP_VU {
            get {
                return this.TRANG_THAI_NGHIEP_VUField;
            }
            set {
                if ((object.ReferenceEquals(this.TRANG_THAI_NGHIEP_VUField, value) != true)) {
                    this.TRANG_THAI_NGHIEP_VUField = value;
                    this.RaisePropertyChanged("TRANG_THAI_NGHIEP_VU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_BAN {
            get {
                return this.TY_GIA_BANField;
            }
            set {
                if ((this.TY_GIA_BANField.Equals(value) != true)) {
                    this.TY_GIA_BANField = value;
                    this.RaisePropertyChanged("TY_GIA_BAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_BQUAN {
            get {
                return this.TY_GIA_BQUANField;
            }
            set {
                if ((this.TY_GIA_BQUANField.Equals(value) != true)) {
                    this.TY_GIA_BQUANField = value;
                    this.RaisePropertyChanged("TY_GIA_BQUAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_DGIA {
            get {
                return this.TY_GIA_DGIAField;
            }
            set {
                if ((this.TY_GIA_DGIAField.Equals(value) != true)) {
                    this.TY_GIA_DGIAField = value;
                    this.RaisePropertyChanged("TY_GIA_DGIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_MUA {
            get {
                return this.TY_GIA_MUAField;
            }
            set {
                if ((this.TY_GIA_MUAField.Equals(value) != true)) {
                    this.TY_GIA_MUAField = value;
                    this.RaisePropertyChanged("TY_GIA_MUA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectChangeTracker", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ObjectChangeTracker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.ExtendedPropertiesDictionary ExtendedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.OriginalValuesDictionary OriginalValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.ObjectState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.ExtendedPropertiesDictionary ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionProperties {
            get {
                return this.ObjectsAddedToCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsAddedToCollectionPropertiesField, value) != true)) {
                    this.ObjectsAddedToCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsAddedToCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionProperties {
            get {
                return this.ObjectsRemovedFromCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsRemovedFromCollectionPropertiesField, value) != true)) {
                    this.ObjectsRemovedFromCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsRemovedFromCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.OriginalValuesDictionary OriginalValues {
            get {
                return this.OriginalValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalValuesField, value) != true)) {
                    this.OriginalValuesField = value;
                    this.RaisePropertyChanged("OriginalValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.ObjectState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, Presentation.Process.TyGiaServiceRef.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, Presentation.Process.TyGiaServiceRef.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework")]
    public enum ObjectState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DANH_SACH_TY_GIA_CT", Namespace="http://schemas.datacontract.org/2004/07/BusinessServices.TyGia.DTO")]
    [System.SerializableAttribute()]
    public partial class DANH_SACH_TY_GIA_CT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HINH_THUC_NIEM_YETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TY_GIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TY_GIA_CTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOAI_TY_GIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_QLYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_TAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_LOAI_TIENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_AP_DUNGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEN_LOAI_TIENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRANG_THAI_BAN_GHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRANG_THAI_NGHIEP_VUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_DLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_BANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_BQUANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_DGIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TY_GIA_MUAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HINH_THUC_NIEM_YET {
            get {
                return this.HINH_THUC_NIEM_YETField;
            }
            set {
                if ((object.ReferenceEquals(this.HINH_THUC_NIEM_YETField, value) != true)) {
                    this.HINH_THUC_NIEM_YETField = value;
                    this.RaisePropertyChanged("HINH_THUC_NIEM_YET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TY_GIA {
            get {
                return this.ID_TY_GIAField;
            }
            set {
                if ((this.ID_TY_GIAField.Equals(value) != true)) {
                    this.ID_TY_GIAField = value;
                    this.RaisePropertyChanged("ID_TY_GIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TY_GIA_CT {
            get {
                return this.ID_TY_GIA_CTField;
            }
            set {
                if ((this.ID_TY_GIA_CTField.Equals(value) != true)) {
                    this.ID_TY_GIA_CTField = value;
                    this.RaisePropertyChanged("ID_TY_GIA_CT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOAI_TY_GIA {
            get {
                return this.LOAI_TY_GIAField;
            }
            set {
                if ((object.ReferenceEquals(this.LOAI_TY_GIAField, value) != true)) {
                    this.LOAI_TY_GIAField = value;
                    this.RaisePropertyChanged("LOAI_TY_GIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_QLY {
            get {
                return this.MA_DVI_QLYField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_QLYField, value) != true)) {
                    this.MA_DVI_QLYField = value;
                    this.RaisePropertyChanged("MA_DVI_QLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_TAO {
            get {
                return this.MA_DVI_TAOField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_TAOField, value) != true)) {
                    this.MA_DVI_TAOField = value;
                    this.RaisePropertyChanged("MA_DVI_TAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_LOAI_TIEN {
            get {
                return this.MA_LOAI_TIENField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_LOAI_TIENField, value) != true)) {
                    this.MA_LOAI_TIENField = value;
                    this.RaisePropertyChanged("MA_LOAI_TIEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_AP_DUNG {
            get {
                return this.NGAY_AP_DUNGField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_AP_DUNGField, value) != true)) {
                    this.NGAY_AP_DUNGField = value;
                    this.RaisePropertyChanged("NGAY_AP_DUNG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_CNHAT {
            get {
                return this.NGAY_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_CNHATField, value) != true)) {
                    this.NGAY_CNHATField = value;
                    this.RaisePropertyChanged("NGAY_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_NHAP {
            get {
                return this.NGAY_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_NHAPField, value) != true)) {
                    this.NGAY_NHAPField = value;
                    this.RaisePropertyChanged("NGAY_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_CNHAT {
            get {
                return this.NGUOI_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_CNHATField, value) != true)) {
                    this.NGUOI_CNHATField = value;
                    this.RaisePropertyChanged("NGUOI_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_NHAP {
            get {
                return this.NGUOI_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_NHAPField, value) != true)) {
                    this.NGUOI_NHAPField = value;
                    this.RaisePropertyChanged("NGUOI_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEN_LOAI_TIEN {
            get {
                return this.TEN_LOAI_TIENField;
            }
            set {
                if ((object.ReferenceEquals(this.TEN_LOAI_TIENField, value) != true)) {
                    this.TEN_LOAI_TIENField = value;
                    this.RaisePropertyChanged("TEN_LOAI_TIEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANG_THAI_BAN_GHI {
            get {
                return this.TRANG_THAI_BAN_GHIField;
            }
            set {
                if ((object.ReferenceEquals(this.TRANG_THAI_BAN_GHIField, value) != true)) {
                    this.TRANG_THAI_BAN_GHIField = value;
                    this.RaisePropertyChanged("TRANG_THAI_BAN_GHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANG_THAI_NGHIEP_VU {
            get {
                return this.TRANG_THAI_NGHIEP_VUField;
            }
            set {
                if ((object.ReferenceEquals(this.TRANG_THAI_NGHIEP_VUField, value) != true)) {
                    this.TRANG_THAI_NGHIEP_VUField = value;
                    this.RaisePropertyChanged("TRANG_THAI_NGHIEP_VU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_DL {
            get {
                return this.TTHAI_DLField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_DLField, value) != true)) {
                    this.TTHAI_DLField = value;
                    this.RaisePropertyChanged("TTHAI_DL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_BAN {
            get {
                return this.TY_GIA_BANField;
            }
            set {
                if ((this.TY_GIA_BANField.Equals(value) != true)) {
                    this.TY_GIA_BANField = value;
                    this.RaisePropertyChanged("TY_GIA_BAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_BQUAN {
            get {
                return this.TY_GIA_BQUANField;
            }
            set {
                if ((this.TY_GIA_BQUANField.Equals(value) != true)) {
                    this.TY_GIA_BQUANField = value;
                    this.RaisePropertyChanged("TY_GIA_BQUAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_DGIA {
            get {
                return this.TY_GIA_DGIAField;
            }
            set {
                if ((this.TY_GIA_DGIAField.Equals(value) != true)) {
                    this.TY_GIA_DGIAField = value;
                    this.RaisePropertyChanged("TY_GIA_DGIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TY_GIA_MUA {
            get {
                return this.TY_GIA_MUAField;
            }
            set {
                if ((this.TY_GIA_MUAField.Equals(value) != true)) {
                    this.TY_GIA_MUAField = value;
                    this.RaisePropertyChanged("TY_GIA_MUA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.TyGiaServiceRef.TyGiaResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ClientType ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.DonViSuDung CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ExceptionObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.ResponseDetail[] ResponseDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseSecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ResponseStatus ResponseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMAC {
            get {
                return this.ClientMACField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientMACField, value) != true)) {
                    this.ClientMACField = value;
                    this.RaisePropertyChanged("ClientMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.DonViSuDung Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((this.CompanyField.Equals(value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeField, value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ExceptionObject {
            get {
                return this.ExceptionObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionObjectField, value) != true)) {
                    this.ExceptionObjectField = value;
                    this.RaisePropertyChanged("ExceptionObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseDateTime {
            get {
                return this.ResponseDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDateTimeField, value) != true)) {
                    this.ResponseDateTimeField = value;
                    this.RaisePropertyChanged("ResponseDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.ResponseDetail[] ResponseDetail {
            get {
                return this.ResponseDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDetailField, value) != true)) {
                    this.ResponseDetailField = value;
                    this.RaisePropertyChanged("ResponseDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseId {
            get {
                return this.ResponseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseIdField, value) != true)) {
                    this.ResponseIdField = value;
                    this.RaisePropertyChanged("ResponseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseSecurityKey {
            get {
                return this.ResponseSecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseSecurityKeyField, value) != true)) {
                    this.ResponseSecurityKeyField = value;
                    this.RaisePropertyChanged("ResponseSecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ResponseStatus ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((this.ResponseStatusField.Equals(value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TyGiaResponse", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.TyGia.Messages")]
    [System.SerializableAttribute()]
    public partial class TyGiaResponse : Presentation.Process.TyGiaServiceRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.DC_TY_GIA[] lstTyGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.DC_TY_GIA objTyGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.TyGiaServiceRef.TY_GIA_CT objTyGiaCTField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.DC_TY_GIA[] lstTyGia {
            get {
                return this.lstTyGiaField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTyGiaField, value) != true)) {
                    this.lstTyGiaField = value;
                    this.RaisePropertyChanged("lstTyGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.DC_TY_GIA objTyGia {
            get {
                return this.objTyGiaField;
            }
            set {
                if ((object.ReferenceEquals(this.objTyGiaField, value) != true)) {
                    this.objTyGiaField = value;
                    this.RaisePropertyChanged("objTyGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.TyGiaServiceRef.TY_GIA_CT objTyGiaCT {
            get {
                return this.objTyGiaCTField;
            }
            set {
                if ((object.ReferenceEquals(this.objTyGiaCTField, value) != true)) {
                    this.objTyGiaCTField = value;
                    this.RaisePropertyChanged("objTyGiaCT");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDetail", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    public partial class ResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TyGiaServiceRef.ITyGiaService")]
    public interface ITyGiaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITyGiaService/TyGia", ReplyAction="http://tempuri.org/ITyGiaService/TyGiaResponse")]
        Presentation.Process.TyGiaServiceRef.TyGiaResponse TyGia(Presentation.Process.TyGiaServiceRef.TyGiaRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITyGiaServiceChannel : Presentation.Process.TyGiaServiceRef.ITyGiaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TyGiaServiceClient : System.ServiceModel.ClientBase<Presentation.Process.TyGiaServiceRef.ITyGiaService>, Presentation.Process.TyGiaServiceRef.ITyGiaService {
        
        public TyGiaServiceClient() {
        }
        
        public TyGiaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TyGiaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TyGiaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TyGiaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Presentation.Process.TyGiaServiceRef.TyGiaResponse TyGia(Presentation.Process.TyGiaServiceRef.TyGiaRequest request) {
            return base.Channel.TyGia(request);
        }
    }
}
