//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Process.ChiTieuServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChiTieuServiceRef.IChiTieuService")]
    public interface IChiTieuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChiTieuService/returnHello", ReplyAction="http://tempuri.org/IChiTieuService/returnHelloResponse")]
        string returnHello();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChiTieuServiceChannel : Presentation.Process.ChiTieuServiceRef.IChiTieuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChiTieuServiceClient : System.ServiceModel.ClientBase<Presentation.Process.ChiTieuServiceRef.IChiTieuService>, Presentation.Process.ChiTieuServiceRef.IChiTieuService {
        
        public ChiTieuServiceClient() {
        }
        
        public ChiTieuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChiTieuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTieuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTieuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string returnHello() {
            return base.Channel.returnHello();
        }
    }
}
