//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Process.UtilitiesServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.UnlockRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.ThamSoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.UtilitiesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.LockRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Action ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ClientType ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.DonViSuDung CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Function FunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MngDeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Module ModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NgayLamViecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OprDeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestSecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.BusinessConstant.LoaiNguoiSuDung UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Action Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMAC {
            get {
                return this.ClientMACField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientMACField, value) != true)) {
                    this.ClientMACField = value;
                    this.RaisePropertyChanged("ClientMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.DonViSuDung Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((this.CompanyField.Equals(value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeField, value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Function Function {
            get {
                return this.FunctionField;
            }
            set {
                if ((this.FunctionField.Equals(value) != true)) {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MngDeptCode {
            get {
                return this.MngDeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MngDeptCodeField, value) != true)) {
                    this.MngDeptCodeField = value;
                    this.RaisePropertyChanged("MngDeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Module Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayLamViec {
            get {
                return this.NgayLamViecField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayLamViecField, value) != true)) {
                    this.NgayLamViecField = value;
                    this.RaisePropertyChanged("NgayLamViec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OprDeptCode {
            get {
                return this.OprDeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OprDeptCodeField, value) != true)) {
                    this.OprDeptCodeField = value;
                    this.RaisePropertyChanged("OprDeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestDateTime {
            get {
                return this.RequestDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDateTimeField, value) != true)) {
                    this.RequestDateTimeField = value;
                    this.RaisePropertyChanged("RequestDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestSecurityKey {
            get {
                return this.RequestSecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestSecurityKeyField, value) != true)) {
                    this.RequestSecurityKeyField = value;
                    this.RaisePropertyChanged("RequestSecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.BusinessConstant.LoaiNguoiSuDung UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnlockRequest", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class UnlockRequest : Presentation.Process.UtilitiesServiceRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ListLockIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Table TableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ListLockId {
            get {
                return this.ListLockIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ListLockIdField, value) != true)) {
                    this.ListLockIdField = value;
                    this.RaisePropertyChanged("ListLockId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Table Table {
            get {
                return this.TableField;
            }
            set {
                if ((this.TableField.Equals(value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThamSoRequest", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class ThamSoRequest : Presentation.Process.UtilitiesServiceRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.BusinessConstant.LoaiThamSo LoaiThamSoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDonViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.BusinessConstant.MaThamSo MaThamSoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.BusinessConstant.LoaiThamSo LoaiThamSo {
            get {
                return this.LoaiThamSoField;
            }
            set {
                if ((this.LoaiThamSoField.Equals(value) != true)) {
                    this.LoaiThamSoField = value;
                    this.RaisePropertyChanged("LoaiThamSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDonVi {
            get {
                return this.MaDonViField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDonViField, value) != true)) {
                    this.MaDonViField = value;
                    this.RaisePropertyChanged("MaDonVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.BusinessConstant.MaThamSo MaThamSo {
            get {
                return this.MaThamSoField;
            }
            set {
                if ((this.MaThamSoField.Equals(value) != true)) {
                    this.MaThamSoField = value;
                    this.RaisePropertyChanged("MaThamSo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilitiesRequest", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class UtilitiesRequest : Presentation.Process.UtilitiesServiceRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string objTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.FormatType typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string objType {
            get {
                return this.objTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.objTypeField, value) != true)) {
                    this.objTypeField = value;
                    this.RaisePropertyChanged("objType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.FormatType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LockRequest", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class LockRequest : Presentation.Process.UtilitiesServiceRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ListLockIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Table TableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ListLockId {
            get {
                return this.ListLockIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ListLockIdField, value) != true)) {
                    this.ListLockIdField = value;
                    this.RaisePropertyChanged("ListLockId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Table Table {
            get {
                return this.TableField;
            }
            set {
                if ((this.TableField.Equals(value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.UnlockResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.ThamSoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.UtilitiesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.UtilitiesServiceRef.LockResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ClientType ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.DonViSuDung CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ExceptionObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.ResponseDetail[] ResponseDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ResponseMessageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseSecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ResponseStatus ResponseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMAC {
            get {
                return this.ClientMACField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientMACField, value) != true)) {
                    this.ClientMACField = value;
                    this.RaisePropertyChanged("ClientMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.DonViSuDung Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((this.CompanyField.Equals(value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeField, value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ExceptionObject {
            get {
                return this.ExceptionObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionObjectField, value) != true)) {
                    this.ExceptionObjectField = value;
                    this.RaisePropertyChanged("ExceptionObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseDateTime {
            get {
                return this.ResponseDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDateTimeField, value) != true)) {
                    this.ResponseDateTimeField = value;
                    this.RaisePropertyChanged("ResponseDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.ResponseDetail[] ResponseDetail {
            get {
                return this.ResponseDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDetailField, value) != true)) {
                    this.ResponseDetailField = value;
                    this.RaisePropertyChanged("ResponseDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseId {
            get {
                return this.ResponseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseIdField, value) != true)) {
                    this.ResponseIdField = value;
                    this.RaisePropertyChanged("ResponseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ResponseMessageData {
            get {
                return this.ResponseMessageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageDataField, value) != true)) {
                    this.ResponseMessageDataField = value;
                    this.RaisePropertyChanged("ResponseMessageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseSecurityKey {
            get {
                return this.ResponseSecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseSecurityKeyField, value) != true)) {
                    this.ResponseSecurityKeyField = value;
                    this.RaisePropertyChanged("ResponseSecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ResponseStatus ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((this.ResponseStatusField.Equals(value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnlockResponse", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class UnlockResponse : Presentation.Process.UtilitiesServiceRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ListUnlockedIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ListUnlockedId {
            get {
                return this.ListUnlockedIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ListUnlockedIdField, value) != true)) {
                    this.ListUnlockedIdField = value;
                    this.RaisePropertyChanged("ListUnlockedId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThamSoResponse", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class ThamSoResponse : Presentation.Process.UtilitiesServiceRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GiaTriThamSoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.HT_TSO objThamSoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GiaTriThamSo {
            get {
                return this.GiaTriThamSoField;
            }
            set {
                if ((object.ReferenceEquals(this.GiaTriThamSoField, value) != true)) {
                    this.GiaTriThamSoField = value;
                    this.RaisePropertyChanged("GiaTriThamSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.HT_TSO objThamSo {
            get {
                return this.objThamSoField;
            }
            set {
                if ((object.ReferenceEquals(this.objThamSoField, value) != true)) {
                    this.objThamSoField = value;
                    this.RaisePropertyChanged("objThamSo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilitiesResponse", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class UtilitiesResponse : Presentation.Process.UtilitiesServiceRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.FormatType typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.UtilitesResponseMessage utilitesResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.FormatType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.UtilitesResponseMessage utilitesResponseMessage {
            get {
                return this.utilitesResponseMessageField;
            }
            set {
                if ((this.utilitesResponseMessageField.Equals(value) != true)) {
                    this.utilitesResponseMessageField = value;
                    this.RaisePropertyChanged("utilitesResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LockResponse", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class LockResponse : Presentation.Process.UtilitiesServiceRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ListLockedIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ListLockedId {
            get {
                return this.ListLockedIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ListLockedIdField, value) != true)) {
                    this.ListLockedIdField = value;
                    this.RaisePropertyChanged("ListLockedId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDetail", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    public partial class ResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HT_TSO", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class HT_TSO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GIA_TRIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTHI_DIEU_KHIENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTHI_DVTINHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTHI_GTRI_MDINHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTHI_POPUPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTHI_SDUNG_TVANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTHI_SQLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KIEU_DU_LIEUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_QLYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_TAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_PHAN_HEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_TSOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_TSO_LOAIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MO_TAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUON_DLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUON_TAO_DLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHAN_LOAIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PVI_AHUONGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEN_TSOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_BGHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_LY_DOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_NVUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GIA_TRI {
            get {
                return this.GIA_TRIField;
            }
            set {
                if ((object.ReferenceEquals(this.GIA_TRIField, value) != true)) {
                    this.GIA_TRIField = value;
                    this.RaisePropertyChanged("GIA_TRI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTHI_DIEU_KHIEN {
            get {
                return this.HTHI_DIEU_KHIENField;
            }
            set {
                if ((object.ReferenceEquals(this.HTHI_DIEU_KHIENField, value) != true)) {
                    this.HTHI_DIEU_KHIENField = value;
                    this.RaisePropertyChanged("HTHI_DIEU_KHIEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTHI_DVTINH {
            get {
                return this.HTHI_DVTINHField;
            }
            set {
                if ((object.ReferenceEquals(this.HTHI_DVTINHField, value) != true)) {
                    this.HTHI_DVTINHField = value;
                    this.RaisePropertyChanged("HTHI_DVTINH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTHI_GTRI_MDINH {
            get {
                return this.HTHI_GTRI_MDINHField;
            }
            set {
                if ((object.ReferenceEquals(this.HTHI_GTRI_MDINHField, value) != true)) {
                    this.HTHI_GTRI_MDINHField = value;
                    this.RaisePropertyChanged("HTHI_GTRI_MDINH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTHI_POPUP {
            get {
                return this.HTHI_POPUPField;
            }
            set {
                if ((object.ReferenceEquals(this.HTHI_POPUPField, value) != true)) {
                    this.HTHI_POPUPField = value;
                    this.RaisePropertyChanged("HTHI_POPUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTHI_SDUNG_TVAN {
            get {
                return this.HTHI_SDUNG_TVANField;
            }
            set {
                if ((object.ReferenceEquals(this.HTHI_SDUNG_TVANField, value) != true)) {
                    this.HTHI_SDUNG_TVANField = value;
                    this.RaisePropertyChanged("HTHI_SDUNG_TVAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTHI_SQL {
            get {
                return this.HTHI_SQLField;
            }
            set {
                if ((object.ReferenceEquals(this.HTHI_SQLField, value) != true)) {
                    this.HTHI_SQLField = value;
                    this.RaisePropertyChanged("HTHI_SQL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KIEU_DU_LIEU {
            get {
                return this.KIEU_DU_LIEUField;
            }
            set {
                if ((object.ReferenceEquals(this.KIEU_DU_LIEUField, value) != true)) {
                    this.KIEU_DU_LIEUField = value;
                    this.RaisePropertyChanged("KIEU_DU_LIEU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_QLY {
            get {
                return this.MA_DVI_QLYField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_QLYField, value) != true)) {
                    this.MA_DVI_QLYField = value;
                    this.RaisePropertyChanged("MA_DVI_QLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_TAO {
            get {
                return this.MA_DVI_TAOField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_TAOField, value) != true)) {
                    this.MA_DVI_TAOField = value;
                    this.RaisePropertyChanged("MA_DVI_TAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_PHAN_HE {
            get {
                return this.MA_PHAN_HEField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_PHAN_HEField, value) != true)) {
                    this.MA_PHAN_HEField = value;
                    this.RaisePropertyChanged("MA_PHAN_HE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_TSO {
            get {
                return this.MA_TSOField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_TSOField, value) != true)) {
                    this.MA_TSOField = value;
                    this.RaisePropertyChanged("MA_TSO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_TSO_LOAI {
            get {
                return this.MA_TSO_LOAIField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_TSO_LOAIField, value) != true)) {
                    this.MA_TSO_LOAIField = value;
                    this.RaisePropertyChanged("MA_TSO_LOAI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MO_TA {
            get {
                return this.MO_TAField;
            }
            set {
                if ((object.ReferenceEquals(this.MO_TAField, value) != true)) {
                    this.MO_TAField = value;
                    this.RaisePropertyChanged("MO_TA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_CNHAT {
            get {
                return this.NGAY_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_CNHATField, value) != true)) {
                    this.NGAY_CNHATField = value;
                    this.RaisePropertyChanged("NGAY_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_NHAP {
            get {
                return this.NGAY_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_NHAPField, value) != true)) {
                    this.NGAY_NHAPField = value;
                    this.RaisePropertyChanged("NGAY_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_CNHAT {
            get {
                return this.NGUOI_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_CNHATField, value) != true)) {
                    this.NGUOI_CNHATField = value;
                    this.RaisePropertyChanged("NGUOI_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_NHAP {
            get {
                return this.NGUOI_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_NHAPField, value) != true)) {
                    this.NGUOI_NHAPField = value;
                    this.RaisePropertyChanged("NGUOI_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUON_DL {
            get {
                return this.NGUON_DLField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUON_DLField, value) != true)) {
                    this.NGUON_DLField = value;
                    this.RaisePropertyChanged("NGUON_DL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUON_TAO_DL {
            get {
                return this.NGUON_TAO_DLField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUON_TAO_DLField, value) != true)) {
                    this.NGUON_TAO_DLField = value;
                    this.RaisePropertyChanged("NGUON_TAO_DL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PHAN_LOAI {
            get {
                return this.PHAN_LOAIField;
            }
            set {
                if ((object.ReferenceEquals(this.PHAN_LOAIField, value) != true)) {
                    this.PHAN_LOAIField = value;
                    this.RaisePropertyChanged("PHAN_LOAI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PVI_AHUONG {
            get {
                return this.PVI_AHUONGField;
            }
            set {
                if ((object.ReferenceEquals(this.PVI_AHUONGField, value) != true)) {
                    this.PVI_AHUONGField = value;
                    this.RaisePropertyChanged("PVI_AHUONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEN_TSO {
            get {
                return this.TEN_TSOField;
            }
            set {
                if ((object.ReferenceEquals(this.TEN_TSOField, value) != true)) {
                    this.TEN_TSOField = value;
                    this.RaisePropertyChanged("TEN_TSO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_BGHI {
            get {
                return this.TTHAI_BGHIField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_BGHIField, value) != true)) {
                    this.TTHAI_BGHIField = value;
                    this.RaisePropertyChanged("TTHAI_BGHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_LY_DO {
            get {
                return this.TTHAI_LY_DOField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_LY_DOField, value) != true)) {
                    this.TTHAI_LY_DOField = value;
                    this.RaisePropertyChanged("TTHAI_LY_DO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_NVU {
            get {
                return this.TTHAI_NVUField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_NVUField, value) != true)) {
                    this.TTHAI_NVUField = value;
                    this.RaisePropertyChanged("TTHAI_NVU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectChangeTracker", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ObjectChangeTracker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.ExtendedPropertiesDictionary ExtendedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.OriginalValuesDictionary OriginalValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.UtilitiesServiceRef.ObjectState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.ExtendedPropertiesDictionary ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionProperties {
            get {
                return this.ObjectsAddedToCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsAddedToCollectionPropertiesField, value) != true)) {
                    this.ObjectsAddedToCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsAddedToCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionProperties {
            get {
                return this.ObjectsRemovedFromCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsRemovedFromCollectionPropertiesField, value) != true)) {
                    this.ObjectsRemovedFromCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsRemovedFromCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.OriginalValuesDictionary OriginalValues {
            get {
                return this.OriginalValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalValuesField, value) != true)) {
                    this.OriginalValuesField = value;
                    this.RaisePropertyChanged("OriginalValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.UtilitiesServiceRef.ObjectState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, Presentation.Process.UtilitiesServiceRef.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, Presentation.Process.UtilitiesServiceRef.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework")]
    public enum ObjectState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckDuplicateRequest", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class CheckDuplicateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GiaTriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenBangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenTruongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GiaTri {
            get {
                return this.GiaTriField;
            }
            set {
                if ((object.ReferenceEquals(this.GiaTriField, value) != true)) {
                    this.GiaTriField = value;
                    this.RaisePropertyChanged("GiaTri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenBang {
            get {
                return this.TenBangField;
            }
            set {
                if ((object.ReferenceEquals(this.TenBangField, value) != true)) {
                    this.TenBangField = value;
                    this.RaisePropertyChanged("TenBang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenTruong {
            get {
                return this.TenTruongField;
            }
            set {
                if ((object.ReferenceEquals(this.TenTruongField, value) != true)) {
                    this.TenTruongField = value;
                    this.RaisePropertyChanged("TenTruong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckDuplicateResponse", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Utilities.Messages")]
    [System.SerializableAttribute()]
    public partial class CheckDuplicateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KetQuaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KetQua {
            get {
                return this.KetQuaField;
            }
            set {
                if ((this.KetQuaField.Equals(value) != true)) {
                    this.KetQuaField = value;
                    this.RaisePropertyChanged("KetQua");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtilitiesServiceRef.IUtilitiesService")]
    public interface IUtilitiesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/IsWorkingDay", ReplyAction="http://tempuri.org/IUtilitiesService/IsWorkingDayResponse")]
        bool IsWorkingDay(System.DateTime value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/LayNgayHopCum", ReplyAction="http://tempuri.org/IUtilitiesService/LayNgayHopCumResponse")]
        System.DateTime[] LayNgayHopCum(int idCum, string ngayDoiChieu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/LayNgayHopCumTheoMa", ReplyAction="http://tempuri.org/IUtilitiesService/LayNgayHopCumTheoMaResponse")]
        System.DateTime[] LayNgayHopCumTheoMa(string maCum, string maDvi, string ngayDoiChieu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/LockData", ReplyAction="http://tempuri.org/IUtilitiesService/LockDataResponse")]
        Presentation.Process.UtilitiesServiceRef.LockResponse LockData(Presentation.Process.UtilitiesServiceRef.LockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/UnlockData", ReplyAction="http://tempuri.org/IUtilitiesService/UnlockDataResponse")]
        Presentation.Process.UtilitiesServiceRef.UnlockResponse UnlockData(Presentation.Process.UtilitiesServiceRef.UnlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/UnlockDataFromFunctionByUser", ReplyAction="http://tempuri.org/IUtilitiesService/UnlockDataFromFunctionByUserResponse")]
        Presentation.Process.UtilitiesServiceRef.UnlockResponse UnlockDataFromFunctionByUser(Presentation.Process.UtilitiesServiceRef.UnlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/UnlockDataFromUser", ReplyAction="http://tempuri.org/IUtilitiesService/UnlockDataFromUserResponse")]
        Presentation.Process.UtilitiesServiceRef.UnlockResponse UnlockDataFromUser(Presentation.Process.UtilitiesServiceRef.UnlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/CheckDuplicateData", ReplyAction="http://tempuri.org/IUtilitiesService/CheckDuplicateDataResponse")]
        Presentation.Process.UtilitiesServiceRef.CheckDuplicateResponse CheckDuplicateData(Presentation.Process.UtilitiesServiceRef.CheckDuplicateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/LayGiaTriThamSo", ReplyAction="http://tempuri.org/IUtilitiesService/LayGiaTriThamSoResponse")]
        Presentation.Process.UtilitiesServiceRef.ThamSoResponse LayGiaTriThamSo(Presentation.Process.UtilitiesServiceRef.ThamSoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/LayThamSo", ReplyAction="http://tempuri.org/IUtilitiesService/LayThamSoResponse")]
        Presentation.Process.UtilitiesServiceRef.ThamSoResponse LayThamSo(Presentation.Process.UtilitiesServiceRef.ThamSoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilitiesService/Utilites", ReplyAction="http://tempuri.org/IUtilitiesService/UtilitesResponse")]
        Presentation.Process.UtilitiesServiceRef.UtilitiesResponse Utilites(Presentation.Process.UtilitiesServiceRef.UtilitiesRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilitiesServiceChannel : Presentation.Process.UtilitiesServiceRef.IUtilitiesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilitiesServiceClient : System.ServiceModel.ClientBase<Presentation.Process.UtilitiesServiceRef.IUtilitiesService>, Presentation.Process.UtilitiesServiceRef.IUtilitiesService {
        
        public UtilitiesServiceClient() {
        }
        
        public UtilitiesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilitiesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitiesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitiesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsWorkingDay(System.DateTime value) {
            return base.Channel.IsWorkingDay(value);
        }
        
        public System.DateTime[] LayNgayHopCum(int idCum, string ngayDoiChieu) {
            return base.Channel.LayNgayHopCum(idCum, ngayDoiChieu);
        }
        
        public System.DateTime[] LayNgayHopCumTheoMa(string maCum, string maDvi, string ngayDoiChieu) {
            return base.Channel.LayNgayHopCumTheoMa(maCum, maDvi, ngayDoiChieu);
        }
        
        public Presentation.Process.UtilitiesServiceRef.LockResponse LockData(Presentation.Process.UtilitiesServiceRef.LockRequest request) {
            return base.Channel.LockData(request);
        }
        
        public Presentation.Process.UtilitiesServiceRef.UnlockResponse UnlockData(Presentation.Process.UtilitiesServiceRef.UnlockRequest request) {
            return base.Channel.UnlockData(request);
        }
        
        public Presentation.Process.UtilitiesServiceRef.UnlockResponse UnlockDataFromFunctionByUser(Presentation.Process.UtilitiesServiceRef.UnlockRequest request) {
            return base.Channel.UnlockDataFromFunctionByUser(request);
        }
        
        public Presentation.Process.UtilitiesServiceRef.UnlockResponse UnlockDataFromUser(Presentation.Process.UtilitiesServiceRef.UnlockRequest request) {
            return base.Channel.UnlockDataFromUser(request);
        }
        
        public Presentation.Process.UtilitiesServiceRef.CheckDuplicateResponse CheckDuplicateData(Presentation.Process.UtilitiesServiceRef.CheckDuplicateRequest request) {
            return base.Channel.CheckDuplicateData(request);
        }
        
        public Presentation.Process.UtilitiesServiceRef.ThamSoResponse LayGiaTriThamSo(Presentation.Process.UtilitiesServiceRef.ThamSoRequest request) {
            return base.Channel.LayGiaTriThamSo(request);
        }
        
        public Presentation.Process.UtilitiesServiceRef.ThamSoResponse LayThamSo(Presentation.Process.UtilitiesServiceRef.ThamSoRequest request) {
            return base.Channel.LayThamSo(request);
        }
        
        public Presentation.Process.UtilitiesServiceRef.UtilitiesResponse Utilites(Presentation.Process.UtilitiesServiceRef.UtilitiesRequest request) {
            return base.Channel.Utilites(request);
        }
    }
}
