//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Process.NganQuyServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NganQuyServiceRef.INganQuyService")]
    public interface INganQuyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INganQuyService/returnHello", ReplyAction="http://tempuri.org/INganQuyService/returnHelloResponse")]
        string returnHello();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INganQuyServiceChannel : Presentation.Process.NganQuyServiceRef.INganQuyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NganQuyServiceClient : System.ServiceModel.ClientBase<Presentation.Process.NganQuyServiceRef.INganQuyService>, Presentation.Process.NganQuyServiceRef.INganQuyService {
        
        public NganQuyServiceClient() {
        }
        
        public NganQuyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NganQuyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NganQuyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NganQuyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string returnHello() {
            return base.Channel.returnHello();
        }
    }
}
