//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.WebClient.WebProcessService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebProcessService.IWebProcessService")]
    public interface IWebProcessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebProcessService/MessageProcess", ReplyAction="http://tempuri.org/IWebProcessService/MessageProcessResponse")]
        long MessageProcess(ref string pv_strMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebProcessServiceChannel : Presentation.WebClient.WebProcessService.IWebProcessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebProcessServiceClient : System.ServiceModel.ClientBase<Presentation.WebClient.WebProcessService.IWebProcessService>, Presentation.WebClient.WebProcessService.IWebProcessService {
        
        public WebProcessServiceClient() {
        }
        
        public WebProcessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebProcessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebProcessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebProcessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long MessageProcess(ref string pv_strMessage) {
            return base.Channel.MessageProcess(ref pv_strMessage);
        }
    }
}
