//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Process.SupportServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.SupportServiceRef.SupportServiceRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Action ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ClientType ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.DonViSuDung CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Function FunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MngDeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.DatabaseConstant.Module ModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NgayLamViecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OprDeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestSecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.BusinessConstant.LoaiNguoiSuDung UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Action Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMAC {
            get {
                return this.ClientMACField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientMACField, value) != true)) {
                    this.ClientMACField = value;
                    this.RaisePropertyChanged("ClientMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.DonViSuDung Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((this.CompanyField.Equals(value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeField, value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Function Function {
            get {
                return this.FunctionField;
            }
            set {
                if ((this.FunctionField.Equals(value) != true)) {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MngDeptCode {
            get {
                return this.MngDeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MngDeptCodeField, value) != true)) {
                    this.MngDeptCodeField = value;
                    this.RaisePropertyChanged("MngDeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.DatabaseConstant.Module Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayLamViec {
            get {
                return this.NgayLamViecField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayLamViecField, value) != true)) {
                    this.NgayLamViecField = value;
                    this.RaisePropertyChanged("NgayLamViec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OprDeptCode {
            get {
                return this.OprDeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OprDeptCodeField, value) != true)) {
                    this.OprDeptCodeField = value;
                    this.RaisePropertyChanged("OprDeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestDateTime {
            get {
                return this.RequestDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDateTimeField, value) != true)) {
                    this.RequestDateTimeField = value;
                    this.RaisePropertyChanged("RequestDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestSecurityKey {
            get {
                return this.RequestSecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestSecurityKeyField, value) != true)) {
                    this.RequestSecurityKeyField = value;
                    this.RaisePropertyChanged("RequestSecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.BusinessConstant.LoaiNguoiSuDung UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Support.Messages")]
    [System.SerializableAttribute()]
    public partial class SupportServiceRequest : Presentation.Process.SupportServiceRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.HT_MENU[] lstMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.HT_MENU objMenuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.HT_MENU[] lstMenu {
            get {
                return this.lstMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.lstMenuField, value) != true)) {
                    this.lstMenuField = value;
                    this.RaisePropertyChanged("lstMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.HT_MENU objMenu {
            get {
                return this.objMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.objMenuField, value) != true)) {
                    this.objMenuField = value;
                    this.RaisePropertyChanged("objMenu");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HT_MENU", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class HT_MENU : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BTUONG_GTRIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BTUONG_TENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_CNANGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_MENU_CHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOAI_PHUONG_THUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_CNANGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_QLYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_DVI_TAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_MENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MA_NNGUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENU_HELPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENU_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGAY_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_CNHATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NGUOI_NHAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NHOM_PHUONG_THUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHAN_LOAIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SO_TTUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEN_MENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEN_PHUONG_THUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_BGHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_LY_DOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TTHAI_NVUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_CATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_GROUPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_HELPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_ICONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BTUONG_GTRI {
            get {
                return this.BTUONG_GTRIField;
            }
            set {
                if ((object.ReferenceEquals(this.BTUONG_GTRIField, value) != true)) {
                    this.BTUONG_GTRIField = value;
                    this.RaisePropertyChanged("BTUONG_GTRI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BTUONG_TEN {
            get {
                return this.BTUONG_TENField;
            }
            set {
                if ((object.ReferenceEquals(this.BTUONG_TENField, value) != true)) {
                    this.BTUONG_TENField = value;
                    this.RaisePropertyChanged("BTUONG_TEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_CNANG {
            get {
                return this.ID_CNANGField;
            }
            set {
                if ((this.ID_CNANGField.Equals(value) != true)) {
                    this.ID_CNANGField = value;
                    this.RaisePropertyChanged("ID_CNANG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_MENU_CHA {
            get {
                return this.ID_MENU_CHAField;
            }
            set {
                if ((this.ID_MENU_CHAField.Equals(value) != true)) {
                    this.ID_MENU_CHAField = value;
                    this.RaisePropertyChanged("ID_MENU_CHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOAI_PHUONG_THUC {
            get {
                return this.LOAI_PHUONG_THUCField;
            }
            set {
                if ((object.ReferenceEquals(this.LOAI_PHUONG_THUCField, value) != true)) {
                    this.LOAI_PHUONG_THUCField = value;
                    this.RaisePropertyChanged("LOAI_PHUONG_THUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_CNANG {
            get {
                return this.MA_CNANGField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_CNANGField, value) != true)) {
                    this.MA_CNANGField = value;
                    this.RaisePropertyChanged("MA_CNANG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_QLY {
            get {
                return this.MA_DVI_QLYField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_QLYField, value) != true)) {
                    this.MA_DVI_QLYField = value;
                    this.RaisePropertyChanged("MA_DVI_QLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_DVI_TAO {
            get {
                return this.MA_DVI_TAOField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_DVI_TAOField, value) != true)) {
                    this.MA_DVI_TAOField = value;
                    this.RaisePropertyChanged("MA_DVI_TAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_MENU {
            get {
                return this.MA_MENUField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_MENUField, value) != true)) {
                    this.MA_MENUField = value;
                    this.RaisePropertyChanged("MA_MENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MA_NNGU {
            get {
                return this.MA_NNGUField;
            }
            set {
                if ((object.ReferenceEquals(this.MA_NNGUField, value) != true)) {
                    this.MA_NNGUField = value;
                    this.RaisePropertyChanged("MA_NNGU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENU_HELP {
            get {
                return this.MENU_HELPField;
            }
            set {
                if ((object.ReferenceEquals(this.MENU_HELPField, value) != true)) {
                    this.MENU_HELPField = value;
                    this.RaisePropertyChanged("MENU_HELP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENU_TYPE {
            get {
                return this.MENU_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.MENU_TYPEField, value) != true)) {
                    this.MENU_TYPEField = value;
                    this.RaisePropertyChanged("MENU_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_CNHAT {
            get {
                return this.NGAY_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_CNHATField, value) != true)) {
                    this.NGAY_CNHATField = value;
                    this.RaisePropertyChanged("NGAY_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGAY_NHAP {
            get {
                return this.NGAY_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGAY_NHAPField, value) != true)) {
                    this.NGAY_NHAPField = value;
                    this.RaisePropertyChanged("NGAY_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_CNHAT {
            get {
                return this.NGUOI_CNHATField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_CNHATField, value) != true)) {
                    this.NGUOI_CNHATField = value;
                    this.RaisePropertyChanged("NGUOI_CNHAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NGUOI_NHAP {
            get {
                return this.NGUOI_NHAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NGUOI_NHAPField, value) != true)) {
                    this.NGUOI_NHAPField = value;
                    this.RaisePropertyChanged("NGUOI_NHAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NHOM_PHUONG_THUC {
            get {
                return this.NHOM_PHUONG_THUCField;
            }
            set {
                if ((object.ReferenceEquals(this.NHOM_PHUONG_THUCField, value) != true)) {
                    this.NHOM_PHUONG_THUCField = value;
                    this.RaisePropertyChanged("NHOM_PHUONG_THUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PHAN_LOAI {
            get {
                return this.PHAN_LOAIField;
            }
            set {
                if ((object.ReferenceEquals(this.PHAN_LOAIField, value) != true)) {
                    this.PHAN_LOAIField = value;
                    this.RaisePropertyChanged("PHAN_LOAI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SO_TTU {
            get {
                return this.SO_TTUField;
            }
            set {
                if ((this.SO_TTUField.Equals(value) != true)) {
                    this.SO_TTUField = value;
                    this.RaisePropertyChanged("SO_TTU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEN_MENU {
            get {
                return this.TEN_MENUField;
            }
            set {
                if ((object.ReferenceEquals(this.TEN_MENUField, value) != true)) {
                    this.TEN_MENUField = value;
                    this.RaisePropertyChanged("TEN_MENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEN_PHUONG_THUC {
            get {
                return this.TEN_PHUONG_THUCField;
            }
            set {
                if ((object.ReferenceEquals(this.TEN_PHUONG_THUCField, value) != true)) {
                    this.TEN_PHUONG_THUCField = value;
                    this.RaisePropertyChanged("TEN_PHUONG_THUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_BGHI {
            get {
                return this.TTHAI_BGHIField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_BGHIField, value) != true)) {
                    this.TTHAI_BGHIField = value;
                    this.RaisePropertyChanged("TTHAI_BGHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_LY_DO {
            get {
                return this.TTHAI_LY_DOField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_LY_DOField, value) != true)) {
                    this.TTHAI_LY_DOField = value;
                    this.RaisePropertyChanged("TTHAI_LY_DO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TTHAI_NVU {
            get {
                return this.TTHAI_NVUField;
            }
            set {
                if ((object.ReferenceEquals(this.TTHAI_NVUField, value) != true)) {
                    this.TTHAI_NVUField = value;
                    this.RaisePropertyChanged("TTHAI_NVU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_CAT {
            get {
                return this.URL_CATField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_CATField, value) != true)) {
                    this.URL_CATField = value;
                    this.RaisePropertyChanged("URL_CAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_GROUP {
            get {
                return this.URL_GROUPField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_GROUPField, value) != true)) {
                    this.URL_GROUPField = value;
                    this.RaisePropertyChanged("URL_GROUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_HELP {
            get {
                return this.URL_HELPField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_HELPField, value) != true)) {
                    this.URL_HELPField = value;
                    this.RaisePropertyChanged("URL_HELP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_ICON {
            get {
                return this.URL_ICONField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_ICONField, value) != true)) {
                    this.URL_ICONField = value;
                    this.RaisePropertyChanged("URL_ICON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_TYPE {
            get {
                return this.URL_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_TYPEField, value) != true)) {
                    this.URL_TYPEField = value;
                    this.RaisePropertyChanged("URL_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectChangeTracker", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ObjectChangeTracker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.ExtendedPropertiesDictionary ExtendedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.OriginalValuesDictionary OriginalValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.ObjectState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.ExtendedPropertiesDictionary ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionProperties {
            get {
                return this.ObjectsAddedToCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsAddedToCollectionPropertiesField, value) != true)) {
                    this.ObjectsAddedToCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsAddedToCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionProperties {
            get {
                return this.ObjectsRemovedFromCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsRemovedFromCollectionPropertiesField, value) != true)) {
                    this.ObjectsRemovedFromCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsRemovedFromCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.OriginalValuesDictionary OriginalValues {
            get {
                return this.OriginalValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalValuesField, value) != true)) {
                    this.OriginalValuesField = value;
                    this.RaisePropertyChanged("OriginalValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.ObjectState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, Presentation.Process.SupportServiceRef.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, Presentation.Process.SupportServiceRef.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework")]
    public enum ObjectState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/DataModel.EntityFramework", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Presentation.Process.SupportServiceRef.SupportServiceResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ClientType ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.DonViSuDung CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ExceptionObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.ResponseDetail[] ResponseDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ResponseMessageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseSecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utilities.Common.ApplicationConstant.ResponseStatus ResponseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMAC {
            get {
                return this.ClientMACField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientMACField, value) != true)) {
                    this.ClientMACField = value;
                    this.RaisePropertyChanged("ClientMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ClientType ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.DonViSuDung Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((this.CompanyField.Equals(value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeField, value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ExceptionObject {
            get {
                return this.ExceptionObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionObjectField, value) != true)) {
                    this.ExceptionObjectField = value;
                    this.RaisePropertyChanged("ExceptionObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseDateTime {
            get {
                return this.ResponseDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDateTimeField, value) != true)) {
                    this.ResponseDateTimeField = value;
                    this.RaisePropertyChanged("ResponseDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.ResponseDetail[] ResponseDetail {
            get {
                return this.ResponseDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDetailField, value) != true)) {
                    this.ResponseDetailField = value;
                    this.RaisePropertyChanged("ResponseDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseId {
            get {
                return this.ResponseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseIdField, value) != true)) {
                    this.ResponseIdField = value;
                    this.RaisePropertyChanged("ResponseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ResponseMessageData {
            get {
                return this.ResponseMessageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageDataField, value) != true)) {
                    this.ResponseMessageDataField = value;
                    this.RaisePropertyChanged("ResponseMessageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseSecurityKey {
            get {
                return this.ResponseSecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseSecurityKeyField, value) != true)) {
                    this.ResponseSecurityKeyField = value;
                    this.RaisePropertyChanged("ResponseSecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Common.ApplicationConstant.ResponseStatus ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((this.ResponseStatusField.Equals(value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/CommunicationServices.Support.Messages")]
    [System.SerializableAttribute()]
    public partial class SupportServiceResponse : Presentation.Process.SupportServiceRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.HT_MENU[] lstMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.Process.SupportServiceRef.HT_MENU objMenuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.HT_MENU[] lstMenu {
            get {
                return this.lstMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.lstMenuField, value) != true)) {
                    this.lstMenuField = value;
                    this.RaisePropertyChanged("lstMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.Process.SupportServiceRef.HT_MENU objMenu {
            get {
                return this.objMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.objMenuField, value) != true)) {
                    this.objMenuField = value;
                    this.RaisePropertyChanged("objMenu");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDetail", Namespace="http://schemas.datacontract.org/2004/07/CommunicationMessages.Base.MessageBases")]
    [System.SerializableAttribute()]
    public partial class ResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupportServiceRef.ISupportService")]
    public interface ISupportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportService/returnHello", ReplyAction="http://tempuri.org/ISupportService/returnHelloResponse")]
        string returnHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportService/Support", ReplyAction="http://tempuri.org/ISupportService/SupportResponse")]
        Presentation.Process.SupportServiceRef.SupportServiceResponse Support(Presentation.Process.SupportServiceRef.SupportServiceRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupportServiceChannel : Presentation.Process.SupportServiceRef.ISupportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupportServiceClient : System.ServiceModel.ClientBase<Presentation.Process.SupportServiceRef.ISupportService>, Presentation.Process.SupportServiceRef.ISupportService {
        
        public SupportServiceClient() {
        }
        
        public SupportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string returnHello() {
            return base.Channel.returnHello();
        }
        
        public Presentation.Process.SupportServiceRef.SupportServiceResponse Support(Presentation.Process.SupportServiceRef.SupportServiceRequest request) {
            return base.Channel.Support(request);
        }
    }
}
